--- #YAML:1.0
name:               UTM5-URFAClient
version:            0.54
abstract:           Perl wrapper for Netup URFA Client
author:
    - VeroLom <ver@0xff.su>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    File::Spec:    0
    Test::Strict:  0
requires:
    Test::More:  0
    XML::Twig:   0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
